$(eval $(call addlib,apphelloworld))

APPHELLOWORLD_SRCS-y += $(APPHELLOWORLD_BASE)/main.c
APPHELLOWORLD_SRCS-y += $(APPHELLOWORLD_BASE)/test.rs

APPHELLOWORLD_SRCS-y += $(APPHELLOWORLD_BASE)/hello_cargo/Cargo.toml

